### ISSUE TITLE
Multiscale modeling overview

### ISSUE THREAD

**Issue by cliffckerr** [starsimhub/hpvsim_orig#294]
- [x] Implement filtering (#49)
- [x] Implement maximally non-random sampling (#234)
- [x] Implement for cancer (#247)
- [x] Check impact on interventions (#297)
- [x] Implement transmission in test script (#295)
- [x] Implement transmission in HPVsim (#296)
