### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by cliffckerr** [starsimhub/hpvsim_orig#377]
- [x] Merge the things that need to be merged, and do a bit more last minute tidying
- [x] Make institutefordiseasemodeling/hpvsim public
- [x] Release on pypi
- [x] Set up [notebook.starsim.org](http://notebook.starsim.org/) that will work for demos for covasim, hpvsim, and fpsim on a clean VM (woodchuck)
- [x] Set up [tutorials.hpvsim.org](http://tutorials.hpvsim.org/) and [tutorials.fpsim.org](http://tutorials.fpsim.org/) that will connect to binder
